apiVersion : apps/v1
kind: Deployment
metadata:
  name: harpreetaulakhpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harpreetaulakhpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: harpreetaulakhpipelinesjavascriptdocker 
    spec:
      containers:
        - name: harpreetaulakhpipelinesjavascriptdocker 
          image: harpreetcontainerrregistry.azurecr.io/harpreetaulakhpipelinesjavascriptdocker
          ports:
          - containerPort: 8080